### ISSUE TITLE
running test script

### ISSUE THREAD

**Issue by francispoulin** [pyboussinesq/TwoDimBoussinesq#1]
Nice work guys.  This looks very slick and I'm looking forward to seeing it evolve (when people have time to push it forward of course).

I git cloned your repo did the old "python setup.py install" but when I went into the scripts directory to run run_model.py it wasn't able to find spectral_model.  I know that I can add this into the path but I'm not sure if that's what you want the user to do.  pyqg seems to do this smoothly so I'm sure that @crocha700 knows how this could be fixed.

python run_model.py 
Traceback (most recent call last):
  File "run_model.py", line 4, in <module>
    import spectral_model as model
ImportError: No module named spectral_model

I realize this is not pressing but thought I would give a small piece of advice.

**Comment by cesar-rocha** [comment]
Thanks for pointing that out @francispoulin 

The problem was with the import in `run_model.py`.  Once the model is installed as a python package, the model class should be imported as

``` python
from TwoDimBoussinesq import spectral_model as model
```

I just fixed this in 0d38f9f .

**Comment by francispoulin** [comment]
Thanks for fixing that @crocha700 .  That did the trick and run_model.py does run.

It did create 10 data files in snapshots.  Is there a script you could post to help us view the data?  I have no h5py experience but am curious to see a graphic of the calculation.

**Comment by cesar-rocha** [comment]
@francispoulin you can do

``` python
import h5py
snap =  h5py.File("000000000000001.h5",'r')

# show the state variables
snap.keys()

# example vorticity
plt.contourf(snap['q'][:])
```
