### ISSUE TITLE
Start a sphinx documentation tree

### ISSUE THREAD

**Issue by cesar-rocha** [pyboussinesq/TwoDimBoussinesq#5]
This can be done a la [pyqg](http://pyqg.readthedocs.org/en/stable/).

**Comment by francispoulin** [comment]
I learned basic sphinx today and it looks great.  Do you know how to create a readthedocs.org link so that we can see the nice formatting of equations on the web?

I have some latex of the equations for this model if you wanted me to throw something together and then you can modify it as much as you like.

**Comment by cesar-rocha** [comment]
> I learned basic sphinx today and it looks great. Do you know how to create a readthedocs.org link so that we can see the nice formatting of equations on the web?

I think we can just enter the repo URL in their [website](https://readthedocs.org)

> I have some latex of the equations for this model if you wanted me to throw something together and then you can modify it as much as you like.

That would be great. Feel free to add anything. I just added you and owner of the repo, so that you can review/merge PRs -- let's follow `pyqg` development workflow (i.e, branching off of master, then implementing the new feature, then submitting a PR)

**Comment by francispoulin** [comment]
I updated a couple of things.  Mainly creating readthedocs and also added some docs with the equations.  When I pushed it I realized afterwards that it was pushed to Masater.  I'm sorry.  Not sure how to undo that.  Next time should I create a dev branch and push it there?

**Comment by francispoulin** [comment]
For some reason the readthedocs didn't work out properly.  Sorry about that.  Will try and figure this out later this evening.  

http://pyboussinesq.readthedocs.org/en/latest/

**Comment by cesar-rocha** [comment]
Thanks @francispoulin.

> When I pushed it I realized afterwards that it was pushed to Master. I'm sorry. Not sure how to undo that. Next time should I create a dev branch and push it there?

No problem, but please don't push stuff directly to master again. Always branch off of master, e.g.,

``` bash
$ git checkout -b add-documentation
```

and then do what you have to do and then submit a pull request. That's the workflow we adopt in `pyqg` and will adopt here. That makes it easier to keep track of changes and revert back if needed.

**Comment by cesar-rocha** [comment]
> For some reason the readthedocs didn't work out properly. Sorry about that. Will try and figure this out later this evening.

What do you mean by "it didn't work properly"? Here it seems to work....

**Comment by francispoulin** [comment]
Very sorry about how i pushed the changes.  I won't do that again.

I am happy to see that it's working now.  Earlier today it wasn't but maybe I just needed it to refresh.

**Comment by cesar-rocha** [comment]
> I am happy to see that it's working now. Earlier today it wasn't but maybe I just needed it to refresh.

I believe it takes some time to build the docs.

I'm closing this since  the documentation tree has been started.
